// Tools Data - 帮小忙 工具箱
// Auto-generated from tool.browser.qq.com

var CATEGORY_META = {
  img: { name: "图片工具", order: 1 },
  pdf: { name: "PDF转换工具", order: 2 },
  data: { name: "数据换算工具", order: 3 },
  life: { name: "生活娱乐工具", order: 4 },
  education: { name: "教育工具", order: 5 },
  text: { name: "文本工具", order: 6 },
  doc: { name: "文档转换工具", order: 7 },
  develop: { name: "开发工具", order: 8 },
  video: { name: "视频工具", order: 9 }
};

var TOOLS_DATA = [
  // ===== 图片工具 (52) =====
  { cat: "img", name: "图片压缩", desc: "图片压缩是一款轻量级的图像压缩工具，能够智能识别图像中的每一个元素，并对它们进行高效的压缩和优化。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_xZTks4xOtEs.png", href: "tupianyasuo.html", style: 1 },
  { cat: "img", name: "证件照生成", desc: "相片生成证件照工具是一款帮助用户快速生成高质量证件照的工具，适用于结婚登记、签证办理、学校报名等。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_PicDW76zOu0.png", href: "id_photo.html", style: 1 },
  { cat: "img", name: "身份证识别", desc: "身份证识别工具通过OCR技术提取证件上的姓名、身份证号码、出生日期等信息。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_MDUSYoySEto.png", href: "identification.html", style: 6 },
  { cat: "img", name: "银行卡识别", desc: "采用尖端银行卡识别技术，快速准确提取银行卡的关键信息，包括卡号、银行名称及有效期等。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_p6IqOrvMTTm.png", href: "bankcard_ocr.html", style: 6 },
  { cat: "img", name: "印刷体识别", desc: "让图片中的文字转化为可编辑格式，精确识别无论字体大小或风格，确保信息无缝转录。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_gdTQ79oWKTn.png", href: "basic_ocr.html", style: 6 },
  { cat: "img", name: "手写体识别", desc: "体验先进的手写体识别工具，轻松转换图片中的手写笔迹为可编辑文本。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_a8OQJaksJMc.png", href: "handwriting_ocr.html", style: 6 },
  { cat: "img", name: "广告体识别", desc: "擅长捕捉商品图片中的文字信息，无论中英文、横排竖排，都能精确返回文本位置和内容。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_2eOmgWGyJDL.png", href: "ocr_advertise.html", style: 6 },
  { cat: "img", name: "英语识别", desc: "精通图像中英文文字的智能检测与识别，无论是印刷体还是手写体都能准确捕捉。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_Q-cyIoIcQ0H.png", href: "ocr_english.html", style: 6 },
  { cat: "img", name: "护照识别", desc: "专业支持中国大陆及港澳台地区乃至全球各国护照个人资料页的精准识别。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_GYwZHyY-y29.png", href: "passport_ocr.html", style: 6 },
  { cat: "img", name: "运单识别", desc: "轻松读取主流电子运单格式，精确提取收寄件人信息、联系电话、地址及运单号等。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_bwWAk_LMCMt.png", href: "waybill.html", style: 6 },
  { cat: "img", name: "集装箱识别", desc: "专业解读箱门信息，全面识别箱号、类型、重量数据等关键字段。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_uj0bsNcBTDj.png", href: "container_ocr.html", style: 6 },
  { cat: "img", name: "车辆证件识别", desc: "精准定位并识别驾驶证、行驶证及机动车登记证书的所有关键字段。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_yiqwLoLgNr3.png", href: "carcard_ocr.html", style: 6 },
  { cat: "img", name: "营业执照识别", desc: "迅速准确捕获执照上的关键信息，如注册号、公司名、地址、法人等。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_zV9iRXwqljo.png", href: "ocr_bizLicense.html", style: 6 },
  { cat: "img", name: "名片识别", desc: "自动定位并精确识别名片上的姓名、联系电话、邮箱、公司名称等信息。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_Xa-mAIuWkev.png", href: "ocr_businesscard.html", style: 6 },
  { cat: "img", name: "港澳台证件识别", desc: "专业支持卡式通行证的全面识别，涵盖签发地、有效期、姓名、证号等字段。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_FXfdcVXdRZY.png", href: "ocr_permit.html", style: 6 },
  { cat: "img", name: "银行回单识别", desc: "精确捕获回单上的交易详情，包括账号、金额、时间等关键信息。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_g57mKU79Tuo.png", href: "bankslip_ocr.html", style: 6 },
  { cat: "img", name: "完税证明识别", desc: "迅速读取并核实证明文件上的关键税务信息，如税种、金额、缴税日期等。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_S-E4c3DYRyj.png", href: "ocr_dutypaidproof.html", style: 6 },
  { cat: "img", name: "医疗票据识别", desc: "专业解析各类医疗票据，自动提取费用、项目、日期等信息。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_t1whl3o9wW0.png", href: "ocr_recognize_medical_invoice.html", style: 6 },
  { cat: "img", name: "网约车行程单识别", desc: "精确捕获行程单上的交易详情，自动化处理，提升财务效率。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_WKT3mAAqfwa.png", href: "onlinetaxi_ocr.html", style: 6 },
  { cat: "img", name: "人脸年龄选择", desc: "一款根据自己照片来改变年龄的在线工具，随心调节照片获取不同年龄的容貌。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_YXiLGmnemJ8.png", href: "face_age_transformation.html", style: 1 },
  { cat: "img", name: "图片编辑器", desc: "集合了多种实用的功能，包括图片裁剪、滤镜、旋转、翻转、画图、添加文字等。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_NWG81zAVmZN.png", href: "img_edit_canvas.html", style: 4 },
  { cat: "img", name: "提取文字", desc: "专业的照片提取文字软件，可以将任何类型的照片中的文本进行提取并保存。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_c-sOAdeCipd.png", href: "ocr.html", style: 5 },
  { cat: "img", name: "图片转字符画", desc: "将任意图片转换为由字符组成的艺术作品，适用于社交媒体分享和个性化设计。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_chCqBm1psyi.png", href: "img_2_text.html", style: 1 },
  { cat: "img", name: "人脸性别转换", desc: "将人脸照片进行性别转换，利用深度学习技术生成逼真的转换效果。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_9O4o8MdD16e.png", href: "face_gender_transformation.html", style: 0 },
  { cat: "img", name: "增加图片大小", desc: "轻松放大图片的大小，同时尽量保持图片的清晰度和质量。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_oK3Pt3u4-vI.png", href: "img_enlarge.html", style: -1 },
  { cat: "img", name: "发票提取", desc: "从pdf或图片中提取发票信息并导出为excel，通过OCR技术自动识别发票数据。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_HLmoKFPY1_u.png", href: "invoice_extract.html", style: 5 },
  { cat: "img", name: "图片日漫滤镜", desc: "将普通照片转换为具有日漫风格的图片，为照片添加日漫滤镜效果。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_gJN5-ADcKpP.png", href: "img_anime_filter.html", style: 0 },
  { cat: "img", name: "头像二次元", desc: "将普通头像照片转换为二次元风格的图片，使其更加生动和个性化。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_SWw-MSqk9IR.png", href: "img_face_anime.html", style: 0 },
  { cat: "img", name: "美化你的头像", desc: "功能强大的在线工具，可以选择喜欢的效果轻松对头像进行美化处理。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_jy_r0gnz3Zo.png", href: "img_module_face_stylize.html", style: 0 },
  { cat: "img", name: "油画滤镜", desc: "将普通照片转换为油画风格的艺术作品，呈现独特的油画质感和艺术氛围。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_XLFzxZRc2Kj.png", href: "img_painting_filter.html", style: 0 },
  { cat: "img", name: "人像分割", desc: "从图片中自动分割出人像，生成透明背景的人像图像。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_yWC7x9Bz_OQ.png", href: "img_human_split.html", style: 0 },
  { cat: "img", name: "照片美化", desc: "免费的图像修饰软件，帮助您修改和润色照片，简单易用人人能上手。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_SYSAuArkyHB.png", href: "img_pic_beauty.html", style: -1 },
  { cat: "img", name: "文档图片扭曲恢复", desc: "修复和校正文档图片中扭曲或变形部分，恢复到原始的平整状态。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_1H8m_YgzcQR.png", href: "doc_wrap.html", style: 0 },
  { cat: "img", name: "图片修复", desc: "免费的图片处理工具，快速修复老化和模糊的照片，恢复到高清状态。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_f4DSnH_HO-_.png", href: "img_fix.html", style: 0 },
  { cat: "img", name: "图片去摩尔纹", desc: "在线免费的图片处理工具，在去除摩尔纹的同时提高图像的质量。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_M2J5h9jX_H3.png", href: "image_enhance.html", style: 0 },
  { cat: "img", name: "多人卡通画", desc: "将自己喜欢的图片添加到卡通风的人物中，创造独特的卡通风人物形象。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_HszKXpby7ZC.png", href: "img_ai_cartoon.html", style: 0 },
  { cat: "img", name: "童话脸", desc: "基于AI技术将照片转换为童话故事中的经典角色形象。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_RRl9fGA-ZCt.png", href: "img_ai_face.html", style: 0 },
  { cat: "img", name: "乔丹风格化", desc: "将普通照片转换为具有迈克尔·乔丹风格的艺术作品。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_s4jgSpaviJz.png", href: "img_ai_jordanstyle.html", style: 0 },
  { cat: "img", name: "国漫水彩风", desc: "将普通照片转换为具有中国漫画水彩风格的艺术作品。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_lVgeM00Yq9E.png", href: "img_ai_watercolor.html", style: 0 },
  { cat: "img", name: "头像挂饰", desc: "在自己的原有头像上增加心仪的挂饰或是DIY定制头像。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_XNyWOe2S0aE.png", href: "avatar_pendant.html", style: 4 },
  { cat: "img", name: "GIF分解", desc: "将GIF动画分解为单帧图片，提取每一帧保存为独立图片文件。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_8fO4_MjP_V3.png", href: "gifsplitter.html", style: 0 },
  { cat: "img", name: "二维码生成", desc: "将文本、URL、联系方式等信息生成二维码，便于分享和使用。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_PzgvtAd45lU.png", href: "qrcode.html", style: 0 },
  { cat: "img", name: "九宫格切图", desc: "将一张图片切割成3x3的九个小图块，适合在社交媒体拼图发布。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_cmelSJs84at.png", href: "img9grid.html", style: 0 },
  { cat: "img", name: "图片格式转换", desc: "在线图片转换工具，可以将图片转换为jpg、png、webp、bmp格式。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_R0GKTfHr0cv.png", href: "imgconvert.html", style: 0 },
  { cat: "img", name: "GIF合成", desc: "多媒体制作工具，将图片通过简单步骤合成为高质量的GIF图。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_fay3s6aaBN4.png", href: "gifcreate.html", style: 0 },
  { cat: "img", name: "二维码美化", desc: "将普通二维码进行美化处理，添加颜色、图标和装饰元素。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_NbORuSIRWN6.png", href: "prettify_qrcode.html", style: 0 },
  { cat: "img", name: "二维码名片", desc: "将个人或企业名片信息生成二维码，便于快速分享和扫描。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_b1zbta6KnO3.png", href: "visit_card.html", style: 0 },
  { cat: "img", name: "图片黑白化", desc: "将图片中的颜色去除，生成具有经典黑白效果的图片。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_13v7iAXB2lY.png", href: "img_fade.html", style: 0 },
  { cat: "img", name: "图片像素化", desc: "将图片进行像素化处理，生成复古、艺术或游戏风格的效果。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_f47CQpCmTBm.png", href: "img_pixel.html", style: -1 },
  { cat: "img", name: "图片隐写", desc: "将文本或文件隐藏在图片中，实现信息的隐秘传输和存储。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_AwJuh3nVpL4.png", href: "image_secret_msg.html", style: -1 },
  { cat: "img", name: "表情包制作", desc: "在线表情包制作工具，制作各种可爱、有趣的图片表情包。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_2hXM0qNkKw6.png", href: "biaoqing.html", style: 4 },
  { cat: "img", name: "二维码扫描", desc: "快速准确读取二维码内嵌的各类数据信息，支持链接、文本、名片等格式。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_PzgvtAd45lU.png", href: "qrcode_scan.html", style: 4 },

  // ===== PDF转换工具 (19) =====
  { cat: "pdf", name: "PDF转Word", desc: "高效的文档处理工具，轻松将PDF文件转换为可编辑的Word文档。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_W4ZZOk76VO4.png", href: "pdf_2_word.html", style: 5 },
  { cat: "pdf", name: "PDF转Excel", desc: "高效的文档处理工具，轻松将PDF文件转换为可编辑的Excel文档。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_fArFtJcyH_q.png", href: "pdf_2_excel.html", style: 5 },
  { cat: "pdf", name: "PDF转HTML", desc: "功能强大的在线转换工具，将PDF中的内容准确转换成网页元素。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_ZCWRH1Nw0p8.png", href: "pdf_2_html.html", style: 0 },
  { cat: "pdf", name: "PDF转图片", desc: "将PDF文档逐页转换为独立的图片文件，或转换为一张连续的长图。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_aCBqbrwMOPk.png", href: "pdf_2_png.html", style: 0 },
  { cat: "pdf", name: "PDF转PPT", desc: "将PDF文件转换成PowerPoint演示文稿，方便在互联网上传播成果。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_pWw6a-OPw2q.png", href: "pdf_2_ppt.html", style: 5 },
  { cat: "pdf", name: "PDF加水印", desc: "在PDF文件上添加自定义的水印信息，保护版权、标记文件状态。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_8yR0OQzXBrS.png", href: "pdf_watermark.html", style: -1 },
  { cat: "pdf", name: "PDF瘦身", desc: "高效压缩PDF大小，减小传输和存储成本，适用于有较多图片的PDF文件。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_G4sqDz6PJDN.png", href: "pdf_compress.html", style: -1 },
  { cat: "pdf", name: "PDF签名", desc: "提供快速、安全的电子签名解决方案，无需打印直接在PDF上添加签名。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_5g6H6j-jWiX.png", href: "pdf_sign.html", style: 4 },
  { cat: "pdf", name: "图片转PDF", desc: "将多张图片合并转换为PDF文件，支持JPG、PNG等图片格式。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_o1X0TOlhWx_.png", href: "img_2_pdf_convert.html", style: -1 },
  { cat: "pdf", name: "PDF拆分", desc: "从PDF文件中提取指定页面并生成新的PDF文件。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_wp-1WMQogcR.png", href: "pdf_split.html", style: 1 },
  { cat: "pdf", name: "PDF合并", desc: "从若干PDF中选择指定页面组成新的PDF。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_Jx9krM7eaJw.png", href: "pdf_merge.html", style: 1 },
  { cat: "pdf", name: "转纯图PDF", desc: "把PDF转为纯图版，防止复制篡改。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_vNXasw6wOSx.png", href: "pdf_imagefy.html", style: -1 },
  { cat: "pdf", name: "PDF页面管理", desc: "轻松添加、删除、旋转PDF页面，并调整页面顺序。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_0jurZRMsuqV.png", href: "pdf_page_manage.html", style: 1 },
  { cat: "pdf", name: "PDF图片提取", desc: "从PDF文件中提取图片，快速高效地保存所需的图片资源。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_HjH58YkDSQ4.png", href: "pdf_img_extract.html", style: -1 },
  { cat: "pdf", name: "PDF加解密", desc: "为PDF文件添加或移除密码保护。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_pPn1P1gH_8U.png", href: "pdf_password.html", style: -1 },
  { cat: "pdf", name: "PDF页面裁剪", desc: "自定义裁剪区域，对PDF的所有页面进行统一裁剪。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_mJHj9uEIKUK.png", href: "pdf_crop.html", style: 4 },
  { cat: "pdf", name: "修改PDF元数据", desc: "修改PDF文件的作者、主题、关键词、内容创作者等信息。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_kcd93i0RsgZ.png", href: "pdf_metadata.html", style: 4 },
  { cat: "pdf", name: "PDF加页码", desc: "为PDF文件的每一页添加页码，提升文档的专业性和可读性。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_gqSSfB6fLGC.png", href: "pdf_page_number.html", style: 4 },
  { cat: "pdf", name: "修改PDF页面尺寸", desc: "修改PDF页面的尺寸，如修改为A3、A4等，方便打印。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_-4BXKyxE-Ld.png", href: "pdf_pagesize.html", style: 4 },

  // ===== 数据换算工具 (13) =====
  { cat: "data", name: "温度转换", desc: "将温度在摄氏度、华氏度和开尔文等单位之间进行转换。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_G5xu26Of335.png", href: "temperaturetrans.html", style: -1 },
  { cat: "data", name: "投资收益计算", desc: "输入投资金额、期限、年化收益率等参数，快速计算投资总收益。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_Diqv6CdiQf0.png", href: "invest.html", style: 0 },
  { cat: "data", name: "五险一金计算", desc: "根据税前月薪、社保基数等参数，计算五险一金缴费金额。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_3Lrlu-aivto.png", href: "wuxianyijin.html", style: 0 },
  { cat: "data", name: "进制转换", desc: "将数字在二进制、八进制、十进制和十六进制之间进行转换。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_cYsjWoCO4z1.png", href: "hexconvert.html", style: 0 },
  { cat: "data", name: "房贷计算", desc: "根据贷款金额、期限、利率等参数，计算每月还款金额。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_iwZScewY9D_.png", href: "mortgage.html", style: 0 },
  { cat: "data", name: "数字大小写转换", desc: "将阿拉伯数字或罗马数字转换为大写或小写形式。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_7pq6Ym5i7u9.png", href: "num2zh.html", style: 0 },
  { cat: "data", name: "BMI计算", desc: "通过体重和身高的比例来评估体重是否在健康范围内。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_nh1Ti_hcpiB.png", href: "bmi.html", style: 0 },
  { cat: "data", name: "时间戳转换", desc: "将时间戳转换为人类可读的日期时间格式，或将日期时间转换为时间戳。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_qFH19V9IwjZ.png", href: "timestamp.html", style: 0 },
  { cat: "data", name: "日期计算", desc: "计算两个日期之间的天数、添加或减去特定天数等。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_xHxN8T3u3Si.png", href: "datecal.html", style: 0 },
  { cat: "data", name: "计算器", desc: "功能强大的计算工具，支持乘除、开方、指数、三角函数等运算。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_kTLJu_AsCBj.png", href: "calculator.html", style: 0 },
  { cat: "data", name: "长度转换", desc: "功能强大的长度换算工具，支持厘米、米、千米、公里等单位。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_GIiWv3h_Se7.png", href: "lengthconvert.html", style: 0 },
  { cat: "data", name: "字节数换算", desc: "在字节、KB、MB、GB、TB等数据单位之间进行转换。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_3Hw5LTxhAU5.png", href: "byte_cal.html", style: -1 },
  { cat: "data", name: "硬盘分区", desc: "对硬盘进行分区管理，创建、调整、删除和格式化硬盘分区。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_HNOkZTi-vQ2.png", href: "partition.html", style: -1 },

  // ===== 生活娱乐工具 (27) =====
  { cat: "life", name: "垃圾分类查询", desc: "查询生活中的垃圾分类情况，了解垃圾分类的具体方法和要求。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_TPJ-H8BOubU.png", href: "garbage.html", style: 1 },
  { cat: "life", name: "搜狗百宝箱", desc: "全能助手！集成日常工具、投资理财、个人信息管理、语言翻译等功能。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_dj6d4Pps5fg.png", href: "sogou_box.html", style: 10 },
  { cat: "life", name: "合同验签", desc: "上传经腾讯电子签完成签署的文件，确保文件自签署之日起未遭篡改。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_DVsaT-OJyqI.png", href: "contract_verification.html", style: 9 },
  { cat: "life", name: "合同对比", desc: "上传原版及新版合同，自动扫描差异，精确定位每一个改动点。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_YYBzI86E6PQ.png", href: "contract_comparison.html", style: 9 },
  { cat: "life", name: "搜狗PDF文件搜索", desc: "在互联网上快速搜索和定位特定的PDF文件。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_qE7QREEXy6k.png", href: "pdf_search.html", style: 4 },
  { cat: "life", name: "今天吃什么", desc: "帮你快速做出吃什么的决定，不用再为每天吃什么而烦恼。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_MsN8VafZqPT.png", href: "whattoeat.html", style: 1 },
  { cat: "life", name: "卡路里查询", desc: "快速查阅各种食物的卡路里含量，帮助进行饮食管理。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_Dyw5N7vkd2Z.png", href: "calories.html", style: 0 },
  { cat: "life", name: "英文创业公司/项目名生成", desc: "根据行业、关键词和风格偏好，生成独特的英文公司或项目名称。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_Nmhjg--B-2N.png", href: "startupname.html", style: 0 },
  { cat: "life", name: "手持弹幕LED", desc: "生成手持LED显示屏上的弹幕内容，用于演唱会、体育赛事等场合。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_uKlrxP6XhFU.png", href: "led.html", style: 0 },
  { cat: "life", name: "文本颜艺", desc: "收录了大量的可爱颜文字，点击即可复制使用。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_5XiSNXdAD6q.png", href: "emoji.html", style: 0 },
  { cat: "life", name: "古诗词取名", desc: "在古诗词中提取灵感，为人名、公司名、项目名等进行命名。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_HACCPtmwZ8C.png", href: "makename.html", style: 0 },
  { cat: "life", name: "车牌归属地", desc: "根据车牌号快速了解车牌属于的省市。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_YMLnLlw29K2.png", href: "carnumber.html", style: 0 },
  { cat: "life", name: "电话区号查询", desc: "提供各地电话区号信息，快速了解所拨打电话属于的地区。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_rGe9zWcCn6Q.png", href: "phonenumber.html", style: 0 },
  { cat: "life", name: "英文人名生成", desc: "快速生成各种不同的英文名字，适用于小说角色、游戏角色等。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_78Zt-jVlA4p.png", href: "fakeword.html", style: 0 },
  { cat: "life", name: "血型遗传规律", desc: "专业的血型遗传查询工具，可以快速计算出后代血型。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_HxrgtyNJVYf.png", href: "bloodtype.html", style: 0 },
  { cat: "life", name: "IP归属地", desc: "快速查找互联网上的IP地址及其对应的地理位置。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_knku2lIcj2M.png", href: "iplocation.html", style: 0 },
  { cat: "life", name: "随机数生成", desc: "根据指定的范围和数量，快速生成一组随机数。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_iqblSwjdrvh.png", href: "random.html", style: 0 },
  { cat: "life", name: "快递查询", desc: "为用户提供便捷的快递信息查询服务，支持实时信息查询。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_sJZUh5Eg6f-.png", href: "kuaidi.html", style: -1 },
  { cat: "life", name: "医院推荐", desc: "根据特定医疗需求推荐合适的医院，查看医院详细信息和用户评价。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_cnKj4siWYcP.png", href: "hospitalrecommend.html", style: -1 },
  { cat: "life", name: "食物热量表", desc: "快速查阅各种食物的热量和营养成分信息。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_H7cCgh6_OoW.png", href: "calories_list.html", style: 0 },
  { cat: "life", name: "食物卡路里", desc: "快速查阅各种食物的卡路里含量，维持健康生活方式。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_qtP78onbR8d.png", href: "food_calories.html", style: 0 },
  { cat: "life", name: "世界时间校准", desc: "查看和校准全球各地的当前时间。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_CYZyJTQPJkw.png", href: "timer.html", style: -1 },
  { cat: "life", name: "随机网名", desc: "提供当前最时尚、潮流的网名供选择。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_nR2znTdzWSQ.png", href: "nick.html", style: -1 },
  { cat: "life", name: "快递信息提取", desc: "从文本中提取快递地址、电话等关键信息。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_ZYbl1AuH89F.png", href: "number_acquisition.html", style: -1 },
  { cat: "life", name: "邮编查询", desc: "查询全国各地的邮政编码信息。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_SxJdZfpPaVd.png", href: "zipcode.html", style: -1 },
  { cat: "life", name: "保质期计算", desc: "输入生产日期和保质期天数，计算出商品的到期日期。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_e-bPbiVnFTw.png", href: "shelflife.html", style: -1 },
  { cat: "life", name: "取名字", desc: "选择自己想要的姓名组合，满足特定的取名需求。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_JWrSWqyHbKc.png", href: "naming.html", style: -1 },

  // ===== 教育工具 (16) =====
  { cat: "education", name: "去手写", desc: "智能识别并抹除文件中的手写内容，还原干净的试卷或文档，方便重新练习或使用。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_PLIH-GtGXkL.png", href: "handwriting_erasure.html", style: 4 },
  { cat: "education", name: "字帖生成", desc: "选择不同的模板、年级，快速生成适合练习书写的字帖。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_mfZWm5RYfb5.png", href: "zitie_new.html", style: 3 },
  { cat: "education", name: "亲戚关系计算", desc: "快速计算两个或多个对象之间复杂的亲戚关系。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_5QJiaZbeCPA.png", href: "relatives_name.html", style: 1 },
  { cat: "education", name: "高校查询", desc: "快速找到中国境内知名大学的相关信息，帮助高考学生和家长们选择学校。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_aI87pFy9qgC.png", href: "school.html", style: 2 },
  { cat: "education", name: "字数计算", desc: "快速计算文本中的字数、字符数、单词数和句子数。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_RT-rk3FR-r3.png", href: "wordcount.html", style: 0 },
  { cat: "education", name: "历史朝代查询", desc: "快速查询和了解各个历史朝代的起止时间、重要事件、著名人物等信息。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_M4UejcjNNLA.png", href: "dynasties.html", style: 0 },
  { cat: "education", name: "各国首都", desc: "快速查询世界各国首都，了解世界地理知识。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_jdB6qNUoFvz.png", href: "capital.html", style: 0 },
  { cat: "education", name: "成语接龙", desc: "帮助您进行成语接龙游戏，提升汉语词汇量和语言表达能力。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_ESsECZTMRls.png", href: "jielong.html", style: -1 },
  { cat: "education", name: "便捷思维导图", desc: "快速创建、编辑和分享思维导图，将想法和知识结构化呈现。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_bQ-p2YBsK6u.png", href: "markmap.html", style: -1 },
  { cat: "education", name: "汉字标准发音", desc: "输入任意汉字或词语，提供标准的拼音和发音。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_JTXa_lLHuPQ.png", href: "hanzifayin.html", style: -1 },
  { cat: "education", name: "元素周期表", desc: "快速查阅化学元素的原子序数、符号、名称、原子量等信息。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_zmxsNOQj-Ex.png", href: "periodic.html", style: 0 },
  { cat: "education", name: "翻译", desc: "将文本从一种语言翻译成另一种语言，支持多种语言。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_evABSEpv1y-.png", href: "translate.html", style: -1 },
  { cat: "education", name: "汉字偏旁", desc: "输入汉字，快速获取偏旁部首信息，了解其构造和意义。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_BAMJebHHnfG.png", href: "radical.html", style: 0 },
  { cat: "education", name: "歇后语", desc: "输入歇后语的前半部分或关键词，快速获取完整歇后语及解释。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_LgMaUNruKSv.png", href: "allegory.html", style: 0 },
  { cat: "education", name: "词语注解", desc: "输入任意词语，获取注解、拼音、词性、例句等信息。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_0LtgddfOhwt.png", href: "explain.html", style: 0 },
  { cat: "education", name: "成语大全", desc: "收录了上亿个成语，能够对成语首字符快速查询。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_UVpYlcJGb3t.png", href: "chengyujielong.html", style: 0 },

  // ===== 文本工具 (7) =====
  { cat: "text", name: "文本转语音", desc: "多功能、高效率的文本转语音在线工具，转换速度快质量高。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_NBRdTyfbzkq.png", href: "tts.html", style: 1 },
  { cat: "text", name: "简体繁体转换", desc: "将简体中文和繁体中文之间进行转换。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_RD4pSnBI2B7.png", href: "chinese.html", style: 0 },
  { cat: "text", name: "文本比较", desc: "比较两个文本内容的差异，找出新增、删除和修改的部分。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_F7W4NJKYDcx.png", href: "textdiff.html", style: 0 },
  { cat: "text", name: "文字转拼音", desc: "将中文文本转换为拼音，便于学习和理解汉字发音。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_1k4MlAY6R8q.png", href: "tta.html", style: 0 },
  { cat: "text", name: "火星文翻译器", desc: "将普通文本转换为火星文，或将火星文转换回普通文本。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_DsPgT4vuZDw.png", href: "toMars.html", style: -1 },
  { cat: "text", name: "文本去重", desc: "快速去除文本中的重复内容，确保文本的唯一性和整洁性。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_BD03AmYZ2G4.png", href: "unique.html", style: -1 },
  { cat: "text", name: "文字隐写", desc: "将文本信息隐藏在其他文本中，实现信息的隐秘传输。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_s73N2Rq-6MZ.png", href: "text_secret_msg.html", style: -1 },

  // ===== 文档转换工具 (9) =====
  { cat: "doc", name: "Word转PDF", desc: "将Microsoft Word文档转换为PDF格式。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_ZY-gWQ56cac.png", href: "word_2_pdf.html", style: 0 },
  { cat: "doc", name: "Word格式转换", desc: "将Word文档转换为图片、HTML及PDF等格式。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_uPdVHC5CWkO.png", href: "word_convert.html", style: 0 },
  { cat: "doc", name: "PPT格式转换", desc: "将PPT文件转换为图片、HTML及PDF等格式。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_8CErxGA80bl.png", href: "ppt_convert.html", style: 0 },
  { cat: "doc", name: "Excel转PDF", desc: "专业的电子表格处理工具，将Excel文件转为PDF文件。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_-LGiOePfa6A.png", href: "excel_to_pdf.html", style: 4 },
  { cat: "doc", name: "文档瘦身", desc: "对文档中的图像进行高效压缩，显著减小文档整体大小。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_WvXh7JVhmPe.png", href: "office_reduce.html", style: 4 },
  { cat: "doc", name: "PPT转PDF", desc: "快速将PowerPoint演示文稿转换为PDF文件。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_KKVR0LhvfMx.png", href: "ppt_2_pdf.html", style: 0 },
  { cat: "doc", name: "Excel格式转换", desc: "将Excel文件转换为其他常见文件格式。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_dvNTssJSmO9.png", href: "excel_convert.html", style: 4 },
  { cat: "doc", name: "图片转Excel", desc: "通过图像识别技术，自动识别图片中的表格内容并转换为Excel。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_F7W4NJKYDcx.png", href: "table_recognize.html", style: 5 },
  { cat: "doc", name: "文档扫描", desc: "将纸质文档或图片转换为数字化的Word电子文档。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_gmTyrp1HHiw.png", href: "word_scan.html", style: 5 },

  // ===== 开发工具 (20) =====
  { cat: "develop", name: "密码安全检测", desc: "输入密码即刻进行全面检测，快速评估密码强度并提供改进建议。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_au5_1WI2dgn.png", href: "password_check.html", style: 7 },
  { cat: "develop", name: "文件安全检测", desc: "上传任意文件，快速识别潜在威胁，确保文件无病毒、无恶意软件。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_SLn3B2xJR8R.png", href: "file_scan.html", style: 7 },
  { cat: "develop", name: "手机安装包检测", desc: "上传手机安装包，提供全面的软件风险查询和行为分析。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_lzHzicUGveV.png", href: "app_inspector.html", style: 7 },
  { cat: "develop", name: "颜色转换", desc: "将多种颜色代码转换为Hex、RGB或HSL格式。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_8G8vjr4flQI.png", href: "colortrans.html", style: -1 },
  { cat: "develop", name: "JSON diff", desc: "比较两个JSON对象之间的差异，适用于配置文件变化、版本控制等。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_W9TfzY7iVfZ.png", href: "jsondiff.html", style: 0 },
  { cat: "develop", name: "JSON校验", desc: "免费高效的JSON检验工具，实时监测和分析JSON文件。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_1e-k0XDsjkj.png", href: "jsoncheck.html", style: 0 },
  { cat: "develop", name: "md5加密", desc: "安全高效的MD5加密工具，帮助保护敏感信息和隐私。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_zW42CaNVFN2.png", href: "md5.html", style: 0 },
  { cat: "develop", name: "Unicode编解码", desc: "将文本进行Unicode编码和解码。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_hVG1krEmUTc.png", href: "unicode.html", style: 0 },
  { cat: "develop", name: "url编解码", desc: "将URL进行编码和解码。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_6LpoMftxySA.png", href: "urlencode.html", style: 0 },
  { cat: "develop", name: "JSON格式化", desc: "将杂乱的JSON数据转换为结构清晰、易于阅读的格式。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_wzKfqyUFXhZ.png", href: "jsonbeautify.html", style: 0 },
  { cat: "develop", name: "在线加解密", desc: "支持多种主流密码算法的加密解密工具。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_swCSu1w47gt.png", href: "crypto.html", style: 0 },
  { cat: "develop", name: "URL解析", desc: "快速理解如何解析常见URL格式，获取域名请求方法。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_0fb8zCCXfrd.png", href: "urlparse.html", style: 0 },
  { cat: "develop", name: "随机密码生成", desc: "根据指定长度和字符类型，生成高强度的随机密码。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_-X1fIIas2Dp.png", href: "pwdgenerator.html", style: 0 },
  { cat: "develop", name: "base64编码", desc: "进行Base64编码和解码，便于网络传输和数据存储。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_THyKkVsmrAS.png", href: "base64.html", style: 0 },
  { cat: "develop", name: "markdown编辑器", desc: "简单易用的Markdown文字处理和排版工具。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_eTqlrsqMyUh.png", href: "markdown.html", style: 0 },
  { cat: "develop", name: "正则校验", desc: "通过突出显示匹配项帮助用户快速定位和修改代码。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_vwDRkSoHN4q.png", href: "regexp.html", style: 0 },
  { cat: "develop", name: "YAML/JSON互相转换", desc: "将YAML格式转换为JSON格式，或JSON转换为YAML。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_jm4NlueoBjd.png", href: "yaml_2_json.html", style: 0 },
  { cat: "develop", name: "userAgent工具", desc: "查看和分析浏览器的User-Agent字符串信息。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_a0t8SFn18Fh.png", href: "useragent.html", style: -1 },
  { cat: "develop", name: "开发语言输出hello world", desc: "快速生成多种编程语言的Hello World示例代码。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_Hn35h7GFAKp.png", href: "compilation.html", style: -1 },
  { cat: "develop", name: "uuid生成", desc: "快速方便地生成唯一标识符UUID。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_-01Gu2Ip0Oy.png", href: "uuid.html", style: -1 },

  // ===== 视频工具 (2) =====
  { cat: "video", name: "在线录屏", desc: "支持录制指定浏览器标签页、指定窗口以及整个屏幕。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_ZmSkjfNIsPZ.png", href: "screen_record.html", style: 4 },
  { cat: "video", name: "视频转gif", desc: "将视频文件转换为GIF动画，便于在社交媒体分享。", icon: "https://m4.publicimg.browser.qq.com/imgUpload/qbtool.t_tool_info/b91aa2df_sAXRKg5B-yj.png", href: "video_2_gif.html", style: 0 }
];

var PLUGINS_DATA = [
  { name: "腾讯会议快捷版", desc: "QQ浏览器用户独享，在侧边栏快捷查看和使用腾讯会议", icon: "https://res.browser.qq.com/qbtool/cms/files/tmeeting-48_1685520498636.png" },
  { name: "腾讯文档快捷版", desc: "办公必备的网站、访问过的文档都在这里。", icon: "https://res.browser.qq.com/qbtool/cms/files/t-doc-m_1685519965316.png" },
  { name: "印象笔记·剪藏", desc: "保存网页信息的最佳工具", icon: "https://stdl.qq.com/stdl/qbextension/qb_logo/3f893295b7ba89ae708f24510384e1bb.png" },
  { name: "历史记录", desc: "在侧边栏显示QQ浏览器历史记录。", icon: "https://m4.publicimg.browser.qq.com/publicimg/pcqb/ext/history-48.png" },
  { name: "Adobe Acrobat", desc: "PDF 编辑、转化、签名工具", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/efaidnbmnnnibpcajpcglclefindmkaj.png" },
  { name: "电脑管家上网防护", desc: "过滤网络不良信息，保护您的上网环境", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ibgigpdnkkdnicediiebbfnednhmlpab.png" },
  { name: "小丰二维码", desc: "方便将网页转换为二维码，也可以识别网页中的二维码。", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/anamdmjnllfgnoamcnlafmhemfcppbbc.png" },
  { name: "健康提醒", desc: "根据营养师推荐的时刻表制作的饮水、眼保健操提醒工具", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/gefpceefdmmojbgmfmnkeanmpclobjgj.png" },
  { name: "NoteExpress网络捕手", desc: "从Chrome浏览器一键保存文献到NoteExpress", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ljbhddngkkppbbkknjldoikonnolgafd.png" },
  { name: "蓝岚日历", desc: "简单实用的生活万年历，包含农历、假日、黄历", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ldabfnoapcgloeobngjnhckcolcfclli.png" },
  { name: "橙光日历", desc: "简单实用的生活万年历，包含农历、假日、黄历", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ocbgooipmfjolciehamjinlnjegkhlko.png" },
  { name: "二维码网址", desc: "点击生成手机可访问的二维码网址", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/apoogihgnkfpeamhldjjoebpphjcmank.png" },
  { name: "EndNote Click", desc: "Fast, one-click access to millions of research papers", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/fjgncogppolhfdpijihbpfmeohpaadpc.png" },
  { name: "有道词典划词插件", desc: "支持Chrome浏览器的划词翻译", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/eopjamdnofihpioajgfdikhhbobonhbb.png" },
  { name: "Web Developer", desc: "Adds a toolbar button with various web developer tools", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/bfbameneiokkgbdmiekhjnmfkcnldhhm.png" },
  { name: "Foxit PDF Creator", desc: "将网页转换为福昕PDF", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/cifnddnffldieaamihfkhkdgnbhfmaci.png" },
  { name: "ACG助手", desc: "提供哔哩哔哩视频下载消息推送", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/kpbnombpnpcffllnianjibmpadjolanh.png" },
  { name: "Tampermonkey", desc: "The world's most popular userscript manager", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/dhdgffkkebhmkfjojejmpbldmpobfkfo.png" },
  { name: "打骨折-淘宝优惠券", desc: "天猫/淘宝商品优惠券一键领取", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/bodhjcioepfmdioecpjonecadajiiamj.png" },
  { name: "关灯看视频", desc: "观看视频时自动调暗页面，仿佛置身于电影院", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/bfbmjmiodbnnpllbbbfblcplfjjepjdn.png" },
  { name: "替换字体中文部分为雅黑", desc: "替换字体的中文部分为雅黑", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/enpkigfhoabjjjonanmddidnnahopmcn.png" },
  { name: "工商银行插件", desc: "ICBC Chrome Extension", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ajmecfihhnibjmmihpecefjjckgbmedh.png" },
  { name: "IDM Integration Module", desc: "Download files with Internet Download Manager", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ngpampappnmepgilojfohadhhmbhlaek.png" },
  { name: "魔方换算", desc: "简单实用的计量单位换算小工具", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/kccajphaffpdfjhgcbccfmcpbgogbknh.png" },
  { name: "Fullscreen Anything", desc: "Maximizes images, videos, and games", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/olcfgpmjldkkjdclidhcbonieibfhhdh.png" },
  { name: "五彩网址二维码", desc: "方便将网页转换为二维码，手机扫描即可浏览", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/kojjendakpnlcgepocgjlmihheljihaj.png" },
  { name: "小说阅读助手", desc: "在浏览器无广告看小说", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/dknlfmhongfkfakmhhnmgfgnhhcbmldm.png" },
  { name: "Avast Online Security", desc: "Avast Browser Security and Web Reputation Plugin", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/gomekmidlodglbbmalcneegieacbdmki.png" },
  { name: "卡巴斯基保护", desc: "在浏览器窗口中管理保护", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ahkjpbeeocnddjkakilopmfdlnjdpcdm.png" },
  { name: "高效网页截图编辑", desc: "截取任意网页，用直线、箭头、文字做标识", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/mdddabjhelpilpnpgondfmehhcplpiin.png" },
  { name: "EditThisCookie", desc: "Cookie管理器，可添加、删除、编辑、搜索cookies", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/fngmhnnpilhplaeedifhccceomclgfbg.png" },
  { name: "Power Automate (Legacy)", desc: "Microsoft web automation add-on", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/gjgfobnenmnljakmhboildkafdkicala.png" },
  { name: "Skype", desc: "Quickly create & join Skype meetings", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/lifbcibllhkdhoafpjfnlhfpfgnpldfl.png" },
  { name: "Power Automate", desc: "Microsoft web automation add-on (v2.27+)", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ljglajjnnkapghbckkcmodicjhacbfhk.png" },
  { name: "ICBC Chrome Extension", desc: "工商银行网上银行Chrome扩展", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/dlombpffcodogboaljnamhpphpdkjdam.png" },
  { name: "高校课程表", desc: "一个带上课提醒的课程表工具", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/diamegoomkocpgkfkmlmegiegkmogpao.png" },
  { name: "店侦探看店宝", desc: "淘宝卖家数据分析工具", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/mndpomcndmohjljbimojnnfnennikjmk.png" },
  { name: "Downloads", desc: "Quick access button to the download page", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/jfchnphgogjhineanplmfkofljiagjfb.png" },
  { name: "金山词霸", desc: "使用金山词霸检索单词，右键查询", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/nggghhclpmecenfkhdflgaaojdacpphj.png" },
  { name: "划词翻译", desc: "划词翻译(可划长句)，使用百度API", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/hkjafmjeochlepgldkncjipkjdhpipbj.png" },
  { name: "喵喵折+", desc: "购物助手，提供商品历史价格、同款比价", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ekbmhggedfdlajiikminikhcjffbleac.png" },
  { name: "下载+", desc: "下载管理快速通道，媒体资源探测下载", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/gokgophibdidjjpildcdbfpmcahilaaf.png" },
  { name: "强制自定义字体", desc: "强制网页使用自定义字体", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/hckjchjpkmbihoocajjpjajkggbccgee.png" },
  { name: "查看源码(zvSource)", desc: "在当前页面弹出层方式查看网页源代码", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ggkbiakmiljlbbfhjajlpjgckcjanbab.png" },
  { name: "搜券助手", desc: "查找淘宝、天猫商品内部优惠券", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/kjkekpkmfhfiokgkjmcdljfomhknpphj.png" },
  { name: "常用工具(ToolBox)", desc: "时间戳转换、URL编码、BASE64编码、二维码生成等", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/fmmbocgmijhikfppllmnamafcphnelgn.png" },
  { name: "划词翻译(多服务)", desc: "支持谷歌、DeepL、ChatGPT等9个翻译服务", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ikhdkkncnoglghljlkmcimlnlhkeamad.png" },
  { name: "Vue.js devtools", desc: "Browser DevTools extension for debugging Vue.js", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/nhdogjmejiglipccpnnnanhbledajbpd.png" },
  { name: "Video Speed Controller", desc: "Speed up, slow down HTML5 audio/video with shortcuts", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/nffaoalbilbmmfgbnbgppjihopabppdk.png" },
  { name: "资源检查", desc: "检查页面资源可访问性的工具", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/pninmpjhjchbpkopdphbkngalhfipaln.png" },
  { name: "视频下载器 CoCoCut", desc: "Chrome专业视频下载器和音乐下载器", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/gddbgllpilhpnjpkdbopahnpealaklle.png" },
  { name: "小乐图客(ZIG)", desc: "图片下载工具5合1：批量取图+拼图+截图+画图+美图", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/gfjhimhkjmipphnaminnnnjpnlneeplk.png" },
  { name: "PDF Viewer", desc: "Uses HTML5 to display PDF files directly in the browser", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/oemmndcbldboiebfnladdacbdfmadadm.png" },
  { name: "Steep and Cheap Timer", desc: "Outdoor gear deals countdown timer", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/aaompibpddahnlhaklkapjkgiajbfkhm.png" },
  { name: "网页截图", desc: "方便快捷地截取整个网页并保存为图像", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/akgpcdalpfphjmfifkmfbpdmgdmeeaeo.png" },
  { name: "Media Hint", desc: "Access the content you need on the internet", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/akipcefbjlmpbcejgdaopmmidpnjlhnb.png" },
  { name: "JSONVue", desc: "Validate and view JSON documents", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/chklaanhfefbnpoihckbnefhakgolnmc.png" },
  { name: "Free Download Manager", desc: "Free Download Manager integration with browser", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ahmpjcflkgiildlgicmcieglgoilbfdp.png" },
  { name: "Zotero Connector", desc: "Save references to Zotero from your web browser", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ekhagklcjbdpajgpjgmbionohlpdbjgc.png" },
  { name: "Pin Them All", desc: "Pin all your tabs", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ndabmaflbdfldmdlccmpccenpkgklhln.png" },
  { name: "Postman Interceptor", desc: "Sends requests fired through the Postman app", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/aicmkgpgakddgnaphhhpliifpcfhicfo.png" },
  { name: "Wikiwand", desc: "Good old Wikipedia gets a great new look", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/emffkefkbkpkgpdeeooapgaicgmcbolj.png" },
  { name: "ColorZilla", desc: "Advanced Eyedropper, Color Picker, Gradient Generator", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/bhlhnicpbhignbdhedgjhgdocnmhomnp.png" },
  { name: "SmoothScroll", desc: "Scroll smoothly on all websites", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/nbokbjkabcmbfdlbddjidfmibcpneigj.png" },
  { name: "IP Domain Country Flag", desc: "Shows country flag and IP/domain information", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/mlpapfcfoakknnhkfpencomejbcecdfp.png" },
  { name: "Video DownloadHelper", desc: "Download Videos from the Web", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/lmjnegcaeklhafolokijcfjliaokphfk.png" },
  { name: "OneTab", desc: "节省高达95%的内存，减轻标签页混乱", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/chphlpgkkbolifaimnlloiipkdnihall.png" },
  { name: "XPath Helper", desc: "Extract, edit, and evaluate XPath queries", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/hgimnogjllphhhkhlmebbmlgjoejdpjl.png" },
  { name: "Keepa", desc: "Amazon Price Tracker with price history charts", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/neebplgakaahbhdphmkckjjcegoiijjo.png" },
  { name: "新榜小助手", desc: "为公众号运营者提供广告接单和运营工具", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/eelnfhegbamoiplojcfjlncmeklaljed.png" },
  { name: "Cloudy Calculator", desc: "A versatile calculator for Chrome", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/acgimceffoceigocablmjdpebeodphgc.png" },
  { name: "IE Tab", desc: "Display web pages using IE within Chrome", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/hehijbfgiekmjfkfjpbkbammjbdenadd.png" },
  { name: "Visualping", desc: "Website change detection and monitoring", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/pemhgklkefakciniebenbfclihhmmfcd.png" },
  { name: "MozBar", desc: "MozBar SEO toolbar from Moz", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/eakacpaijcpapndcfffdgphdiccmpknp.png" },
  { name: "Advanced Font Settings", desc: "Customize per-script font settings", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/caclkomlalccbpcdllchkeecicepbmbm.png" },
  { name: "下载Vimeo视频", desc: "可下载任何Vimeo视频的专业下载器", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/phpaiffimemgakmakpcehgbophkbllkf.png" },
  { name: "SEOquake", desc: "Free plugin providing key SEO metrics", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/akdgnmcogleenhbclghghlkkdndkjdjc.png" },
  { name: "TinEye Reverse Image Search", desc: "Find out where an image came from", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/haebnnbpedcbhciplfhjjkbafijpncjl.png" },
  { name: "iGive Button", desc: "Turn shopping into free donations for charity", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/igcjdamjhkmdccbmbilbpabpofenchge.png" },
  { name: "Chrome Logger", desc: "Server side logging and debugging in chrome console", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/noaneddfkdjfnfdakjjmocngnfkfehhd.png" },
  { name: "Text Mode", desc: "Browse the web via simple text based pages", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/adelhekhakakocomdfejiipdnaadiiib.png" },
  { name: "Neater Bookmarks", desc: "灵巧实用的弹出书签", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ofgjggbjanlhbgaemjbkiegeebmccifi.png" },
  { name: "QR Code Extension", desc: "生成QR码，并使用摄像头扫描QR码", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/oijdcdmnjjgnnhgljmhkjlablaejfeeb.png" },
  { name: "User-Agent Switcher", desc: "Switches User-Agent strings to mimic other browsers", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/lkmofgnohbedopheiphabfhfjgkhfcgf.png" },
  { name: "Fine Link Selector", desc: "Make it easy to select a part of link texts", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/adcehildlgkafghlmnbnhegagachlioe.png" },
  { name: "Session Buddy", desc: "Manage Browser Tabs and Bookmarks with Ease", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/edacconmaakjimmfgnblocblbcdcpbko.png" },
  { name: "超级下单", desc: "万能的一件代发下单神器", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/dllgocogbblembnhmkbjbakkfkooficl.png" },
  { name: "Scraper", desc: "Gets data out of web pages and into spreadsheets", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/mbigbapnjcgaffohmbkdlecaccepngjd.png" },
  { name: "WizClipper", desc: "为知笔记网页剪辑工具", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/jfanfpmalehkemdiiebjljddhgojhfab.png" },
  { name: "start.me新标签页", desc: "完全个性化起始页", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/cfmnkhhioonhiehehedmnjibmampjiab.png" },
  { name: "Bitly", desc: "Short links and QR Codes", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/iabeihobmhlgpkcgjiloemdbofjbdcic.png" },
  { name: "FeHelper(前端助手)", desc: "JSON格式化、编解码、下载等前端开发工具集", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/pkgccpejnmalmdinmhkkfafefagiiiad.png" },
  { name: "Dark Reader", desc: "适用于任何网站的黑暗主题，关爱眼睛", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/eimadpbcbfnmbkopoojfekhnkhdbieeh.png" },
  { name: "Octotree", desc: "GitHub code tree browser", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/bkhaagjahfmjljalopjnoealnfndnagc.png" },
  { name: "音量增加", desc: "将声音放大高达600%，使用音频均衡器控制声音", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ogadflejmplcdhcldlloonbiekhnlopp.png" },
  { name: "花瓣采集插件", desc: "从任意网站采集图片、视频到花瓣网", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/fgobbidklammfajebkefikkdhblbaaam.png" },
  { name: "Eagle for Chrome", desc: "轻松保存图像和屏幕截图到Eagle App", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/lieogkinebikhdchceieedcigeafdkid.png" },
  { name: "Global Speed", desc: "设置视频和音频的默认速度", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/jpbjcnkcffbooppibceonlgknpkniiff.png" },
  { name: "Autofill", desc: "最受欢迎的自动填表扩展", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/nlmmgnhgdeffjkdckmikfpnddkbbfkkk.png" },
  { name: "Grid Ruler", desc: "Create grids and measure their distance easily", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/joadogiaiabhmggdifljlpkclnpfncmj.png" },
  { name: "Bitwarden", desc: "安全且免费的跨平台密码管理器", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/nngceckbapebfimnlniiiahkandclblb.png" },
  { name: "LastPass", desc: "Free Password Manager，saves your passwords securely", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/hdokiejnpimakedhajhdlcegeplioahd.png" },
  { name: "Awesome 护眼模式", desc: "为最流行的网站提供护眼模式", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ongbbdkcjoainajbfkcnedkbahjoecll.png" },
  { name: "Workona Tab Manager", desc: "The world's best tab manager", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/ailcmbgekjpnablpdkmaaccecekgdhlh.png" },
  { name: "Tab Manager Plus", desc: "Quickly find open tabs, see all windows in one view", icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/pc_chomre_icon/cnkdjjdmfiffagllbiiilooaoofcoeff.png" },
  { name: "AudioMax声音增强器", desc: "提高音量，增强低音，多功能均衡器", icon: "https://res.browser.qq.com/qbtool/cms/files/bdbedpgdcnjmnccdappdddadbcdichio_1695284347958.png" },
  { name: "腾讯 CoDesign 采集", desc: "图片素材云端管理，支持多种素材格式采集", icon: "https://res.browser.qq.com/qbtool/cms/files/oaepbcehadahoekoceooailhlgpkndej_1695284619832.png" },
  { name: "好网角收藏夹", desc: "右键一键快照网页链接，网页失效也不丢失", icon: "https://res.browser.qq.com/qbtool/cms/files/chrome_icon_128x128_1711678228589.png" },
  { name: "迅雷下载支持", desc: "迅雷X接管Chrome浏览器的下载请求", icon: "https://res.browser.qq.com/qbtool/cms/files/unnamed_1727359082639.png" }
];
